export const categoryNames: string[] = [
  'Groceries', 'Car', 'Transportation', 'Cash', 'Gas', 'Restaurants', 'Needs', 'Wants', 'Savings', 'Transportation',
  'Car', 'Gas', 'Parking Fees', 'Housing', 'Rent', 'Mortgage', 'Property Taxes', 'Taxes', 'Household', 'House', 'Repairs',
  'Food', 'Utilities', 'Bills', 'Electricity', 'Water', 'Garbage', 'Phones', 'Cable', 'Internet', 'Subscription', 'Subscriptions',
  'Netflix', 'Hulu', 'Disney+', 'Google', 'Adobe', 'Clothing', 'Clothes', 'Healthcare', 'Health', 'Insurance', 'Household Repairs',
  'Personal', 'Education', 'Gym membership', 'Gym', 'Haircut', 'Haircuts', 'Debt', 'Entertainment', 'Movie', 'Movies', 'Film',
  'Films', 'Retirement', 'Fund', 'Donations', 'Gifts', 'Gifts and Donations', 'Cash Deposit', 'Salary', 'Freelance', 'Job',
  'Income source', 'Cash withdraw', 'Groceries', 'Eating Out', 'Restaurants', 'Dining', 'Travel', 'Vacation', 'Holidays',
  'Leisure', 'Recreation', 'Hobbies', 'Pet Expenses', 'Pet Care', 'Veterinary', 'Childcare', 'Education', 'Tuition', 'Books',
  'School Supplies', 'Loans', 'Credit Card Payments', 'Interest', 'Investments', 'Stocks', 'Bonds', 'Mutual Funds', 'Dividends',
  'Retirement Savings', 'IRA', '401(k)', 'Health Savings Account (HSA)', 'Taxes', 'Income Taxes', 'Tax Deductions', 'Insurance',
  'Auto Insurance', 'Home Insurance', 'Life Insurance', 'Health Insurance', 'Disability Insurance', 'Personal Care', 'Beauty',
  'Cosmetics', 'Electronics', 'Technology', 'Internet Services', 'Mobile Phone', 'Cell Phone', 'Communication', 'Charities',
  'Philanthropy', 'Subscriptions', 'Memberships', 'Streaming Services', 'Music', 'Magazines', 'Newspapers', 'Books', 'E-books',
  'Home Decor', 'Furniture', 'Appliances', 'Renovations', 'Travel Expenses', 'Airfare', 'Accommodation', 'Car Rental',
  'Transportation', 'Commuting', 'Public Transportation', 'Fuel', 'Car Maintenance', 'Repairs', 'Health Expenses',
  'Medical Bills', 'Prescription Medication', 'Dental Care', 'Vision Care', 'Fitness', 'Gym Membership', 'Exercise Equipment',
  'Outdoor Activities', 'Sports', 'Taxes', 'Professional Services', 'Legal Fees', 'Accounting', 'Financial Planning',
  'Professional Development', 'Training', 'Work-related Expenses', 'Business Expenses', 'Marketing', 'Advertising',
  'Miscellaneous', 'Gifts', 'Donations', 'Charitable Contributions', 'Cash Withdrawal', 'Savings Goals', 'Emergency Fund',
  'Miscellaneous Income', 'Side Hustles', 'Miscellaneous Expenses', 'Investment Income', 'Rental Income', 'Royalties', 'Alimony',
  'Child Support', 'Miscellaneous Income', 'Refunds', 'Rebates', 'Cash Back', 'Lottery Winnings', 'Gambling', 'Fine Arts',
  'Collectibles', 'Antiques', 'Home Maintenance', 'Lawn Care', 'Landscaping', 'Home Improvement', 'Home Security', 'Pest Control',
  'Homeowners Association (HOA) Fees', 'Home Warranty', 'Furniture', 'Appliances', 'Electronics', 'Computers', 'Software',
  'Office Supplies', 'Stationery', 'Printing', 'Shipping', 'Postage', 'Utilities', 'Natural Gas', 'Heating', 'Air Conditioning',
  'Home Cleaning', 'Laundry', 'Dry Cleaning', 'Storage', 'Self-Storage', 'Homeowners Insurance', 'Renters Insurance',
  'Auto Maintenance', 'Car Insurance', 'Registration', 'Licenses', 'Car Wash', 'Tolls', 'Public Parking', 'Professional Fees',
  'Consulting', 'Coaching', 'Mentoring', 'Subcontractors', 'Taxes', 'Real Estate Taxes', 'Property Insurance', 'Legal Fees',
  'Medical Insurance', 'Prescription Medications', 'Health Supplements', 'Alternative Therapies', 'Therapy', 'Counseling',
  'Personal Development', 'Self-Care', 'Spa', 'Retreats', 'Salon', 'Electronics', 'Gadgets', 'Streaming Devices',
  'Video Games', 'Software Subscriptions', 'Photography', 'Camera Equipment', 'Travel Insurance', 'Foreign Exchange', 'Visas',
  'Immigration Fees', 'Moving Expenses', 'Utilities Setup Fees', 'Home Internet Setup Fees', 'Vehicle Purchase', 'Vehicle Lease',
  'Vehicle Rental', 'Uber/Lyft', 'Public Transportation Passes', 'Child Expenses', 'School Fees', 'Extracurricular Activities',
  'Birthday Parties', 'Toys', 'Childcare Supplies', 'Baby Gear', 'Elderly Care', 'Senior Living', 'Assisted Living',
  'Home Modifications', 'Funeral Expenses', 'Weddings', 'Engagement Rings', 'Bridal Shower', 'Bachelor/Bachelorette Party',
  'Wedding Photography', 'Catering', 'Party Supplies', 'Event Tickets', 'Concerts', 'Theater', 'Museums', 'Art Exhibitions',
  'Outdoor Events', 'Festivals', 'Home Security', 'Security Systems', 'Alarm Monitoring', 'Safety Equipment', 'Donations',
  'Contributions', 'Religious Offerings', 'Membership Dues', 'Social Club Fees', 'Online Courses', 'Certifications', 'Workshops',
  'Webinars', 'Digital Products', 'Marketing Tools', 'Advertising Campaigns', 'Business Travel', 'Meals and Entertainment',
  'Client Gifts', 'Office Rent', 'Office Maintenance', 'Office Equipment', 'Utilities', 'Professional Subscriptions',
  'Continuing Education', 'Business Insurance', 'Copyrights', 'Trademarks', 'Licenses', 'Patents', 'Professional Memberships',
  'Amazon Prime Video', 'Hulu', 'Disney+', 'HBO Max', 'Apple TV+', 'YouTube Premium', 'Spotify Premium', 'Pandora Premium',
  'Tidal', 'Apple Music', 'Google Play Music', 'Amazon Music Unlimited', 'Audible', 'Kindle Unlimited', 'Scribd', 'Texture',
  'Texture+', 'Adobe Creative Cloud', 'Microsoft Office 365', 'Dropbox', 'Evernote Premium', 'Trello Gold', 'Todoist Premium',
  'LastPass Premium', 'Grammarly Premium', 'Headspace', 'Calm', 'Duolingo Plus', 'Skillshare Premium', 'Coursera Plus',
  'MasterClass', 'LinkedIn Learning', 'Rosetta Stone', 'Babbel', 'The New York Times Digital Subscription',
  'The Wall Street Journal Digital Subscription', 'The Washington Post Digital Subscription',
  'The Economist Digital Subscription', 'National Geographic+', 'Vogue Magazine Subscription',
  'Netflix DVD Subscription', 'GameFly', 'Birchbox', 'Ipsy', 'BarkBox', 'Stitch Fix', 'Dollar Shave Club', 'Blue Apron',
  'HelloFresh', 'Home Chef', 'Freshly', 'Instacart Express', 'Postmates Unlimited', 'Uber Pass', 'DoorDash DashPass',
  'Grubhub+', 'Airbnb Plus', 'VRV Premium', 'Crunchyroll Premium', 'WWE Network', 'NFL Game Pass', 'NBA League Pass',
  'NHL.TV', 'MLB.TV', 'UFC Fight Pass', 'WWE Network', 'PlayStation Plus', 'Xbox Game Pass', 'Nintendo Switch Online', 'Steam'
];
